Add missing PyQt6.uic module for runtime
Closes: 1023163

calibre, version 6.7.1
ERROR: Unhandled exception: <b>ModuleNotFoundError</b>:No module named 'PyQt6.uic'

calibre 6.7.1  embedded-python: False
Linux-5.19.1-stb-cbq+-aarch64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.19.1-stb-cbq+', '#3 SMP PREEMPT Wed Aug 17 02:45:48 UTC 2022')
Python 3.10.8
Interface language: None
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/actions/catalog.py", line 51, in generate_catalog
    ret = generate_catalog(self.gui, dbspec, ids, self.gui.device_manager,
  File "/usr/lib/calibre/calibre/gui2/tools.py", line 328, in generate_catalog
    d = Catalog(parent, dbspec, ids, db)
  File "/usr/lib/calibre/calibre/gui2/dialogs/catalog.py", line 28, in __init__
    from PyQt6.uic import compileUi
ModuleNotFoundError: No module named 'PyQt6.uic'